In [2]:
import os as o
t=o.getcwd()
t

'C:\\Users\\ELCOT'

In [3]:
g=o.chdir(r'C:\Users\ELCOT\Downloads')
t=o.getcwd()
t

'C:\\Users\\ELCOT\\Downloads'

In [20]:
import pandas as pd
data=pd.read_csv('bank.csv')
data

,transaction_id,account_id,customer_age,account_type,transaction_date,transaction_type,channel,amount_usd,merchant_category,is_fraud_flagged,balance_after_txn_usd
0,TXN_FIN_10000,ACC_0134,24,Savings,2024-09-16,Deposit,Mobile App,788.91,Travel,0,47578.64
1,TXN_FIN_10001,ACC_0135,47,Investment,2024-04-04,Transfer,Online Banking,102.45,Groceries,0,47621.97
2,TXN_FIN_10002,ACC_0170,18,Savings,2024-01-30,Withdrawal,Online Banking,108.72,Retail,0,18057.86
3,TXN_FIN_10003,ACC_0089,72,Checking,2024-01-16,NaN,Mobile App,156.57,Retail,0,3878.63
4,TXN_FIN_10004,ACC_0157,35,Savings,2024-04-28,Withdrawal,Mobile App,537.51,Retail,0,26920.71
...,...,...,...,...,...,...,...,...,...,...,...
1500,TXN_FIN_10003,ACC_0089,72,Checking,2024-01-16,NaN,Mobile App,156.57,Retail,0,3878.63
1501,TXN_FIN_10017,ACC_0098,41,Checking,2024-10-14,Withdrawal,ATM,761.41,Retail,0,39404.64
1502,TXN_FIN_10092,ACC_0127,28,Investment,2024-12-21,Deposit,Mobile App,521.36,Entertainment,0,3978.59
1503,TXN_FIN_10104,ACC_0095,62,Savings,2024-11-23,Withdrawal,Online Banking,88.68,Retail,0,17781.35
1504,TXN_FIN_10250,ACC_0039,41,Investment,2024-03-29,Transfer,ATM,186.26,Groceries,0,26702.80

In [21]:
#find null,duplicates
print(data.shape)
print(data.isnull().sum())
print(data.duplicated().sum())
print(data.loc[data.duplicated()])

(1505, 11)
transaction_id            0
account_id                0
customer_age              0
account_type              0
transaction_date          0
transaction_type         74
channel                   0
amount_usd                0
merchant_category        83
is_fraud_flagged          0
balance_after_txn_usd     0
dtype: int64
5
     transaction_id account_id  customer_age account_type transaction_date  \
1500  TXN_FIN_10003   ACC_0089            72     Checking       2024-01-16
1501  TXN_FIN_10017   ACC_0098            41     Checking       2024-10-14
1502  TXN_FIN_10092   ACC_0127            28   Investment       2024-12-21
1503  TXN_FIN_10104   ACC_0095            62      Savings       2024-11-23
1504  TXN_FIN_10250   ACC_0039            41   Investment       2024-03-29

     transaction_type         channel  amount_usd merchant_category  \
1500              NaN      Mobile App      156.57            Retail
1501       Withdrawal             ATM      761.41            Retail
1502          Deposit      Mobile App      521.36     Entertainment
1503       Withdrawal  Online Banking       88.68            Retail
1504         Transfer             ATM      186.26         Groceries

      is_fraud_flagged  balance_after_txn_usd
1500                 0                3878.63
1501                 0               39404.64
1502                 0                3978.59
1503                 0               17781.35
1504                 0               26702.80

In [22]:
# data=data.dropna()
# print(data.isnull().sum())
# data=data.drop_duplicates()
# data

In [23]:
# clean null,duplicate
data['transaction_type']=data['transaction_type'].fillna('unknown')
data['merchant_category']=data['merchant_category'].fillna('unknown')
print(data.isnull().sum())
data=data.drop_duplicates()
data

transaction_id           0
account_id               0
customer_age             0
account_type             0
transaction_date         0
transaction_type         0
channel                  0
amount_usd               0
merchant_category        0
is_fraud_flagged         0
balance_after_txn_usd    0
dtype: int64

,transaction_id,account_id,customer_age,account_type,transaction_date,transaction_type,channel,amount_usd,merchant_category,is_fraud_flagged,balance_after_txn_usd
0,TXN_FIN_10000,ACC_0134,24,Savings,2024-09-16,Deposit,Mobile App,788.91,Travel,0,47578.64
1,TXN_FIN_10001,ACC_0135,47,Investment,2024-04-04,Transfer,Online Banking,102.45,Groceries,0,47621.97
2,TXN_FIN_10002,ACC_0170,18,Savings,2024-01-30,Withdrawal,Online Banking,108.72,Retail,0,18057.86
3,TXN_FIN_10003,ACC_0089,72,Checking,2024-01-16,unknown,Mobile App,156.57,Retail,0,3878.63
4,TXN_FIN_10004,ACC_0157,35,Savings,2024-04-28,Withdrawal,Mobile App,537.51,Retail,0,26920.71
...,...,...,...,...,...,...,...,...,...,...,...
1495,TXN_FIN_11495,ACC_0038,68,Checking,2024-12-24,Payment,Online Banking,557.69,Entertainment,0,47714.65
1496,TXN_FIN_11496,ACC_0119,56,Credit Card,2024-11-05,Payment,Online Banking,230.16,Groceries,0,2167.28
1497,TXN_FIN_11497,ACC_0160,46,Savings,2024-12-22,Payment,Mobile App,801.84,Travel,0,29646.94
1498,TXN_FIN_11498,ACC_0076,39,Savings,2024-10-14,Payment,ATM,55.91,Entertainment,0,15156.76
1499,TXN_FIN_11499,ACC_0023,78,Savings,2024-12-26,Payment,Online Banking,8.80,Utilities,0,49264.64

In [24]:
data['balance_before_txn_usd']=data['balance_after_txn_usd']-data['amount_usd']
data

,transaction_id,account_id,customer_age,account_type,transaction_date,transaction_type,channel,amount_usd,merchant_category,is_fraud_flagged,balance_after_txn_usd,balance_before_txn_usd
0,TXN_FIN_10000,ACC_0134,24,Savings,2024-09-16,Deposit,Mobile App,788.91,Travel,0,47578.64,46789.73
1,TXN_FIN_10001,ACC_0135,47,Investment,2024-04-04,Transfer,Online Banking,102.45,Groceries,0,47621.97,47519.52
2,TXN_FIN_10002,ACC_0170,18,Savings,2024-01-30,Withdrawal,Online Banking,108.72,Retail,0,18057.86,17949.14
3,TXN_FIN_10003,ACC_0089,72,Checking,2024-01-16,unknown,Mobile App,156.57,Retail,0,3878.63,3722.06
4,TXN_FIN_10004,ACC_0157,35,Savings,2024-04-28,Withdrawal,Mobile App,537.51,Retail,0,26920.71,26383.20
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,TXN_FIN_11495,ACC_0038,68,Checking,2024-12-24,Payment,Online Banking,557.69,Entertainment,0,47714.65,47156.96
1496,TXN_FIN_11496,ACC_0119,56,Credit Card,2024-11-05,Payment,Online Banking,230.16,Groceries,0,2167.28,1937.12
1497,TXN_FIN_11497,ACC_0160,46,Savings,2024-12-22,Payment,Mobile App,801.84,Travel,0,29646.94,28845.10
1498,TXN_FIN_11498,ACC_0076,39,Savings,2024-10-14,Payment,ATM,55.91,Entertainment,0,15156.76,15100.85
1499,TXN_FIN_11499,ACC_0023,78,Savings,2024-12-26,Payment,Online Banking,8.80,Utilities,0,49264.64,49255.84

In [32]:
t=data.groupby('transaction_type')[['balance_after_txn_usd','balance_before_txn_usd']].agg(['sum','count','min','max','mean'])
t

                 balance_after_txn_usd                                         \
                                   sum count      min       max          mean
transaction_type
Deposit                    11437782.94   474   158.76  49999.78  24130.343755
Payment                     5995291.85   236   130.99  49621.96  25403.779025
Transfer                    6965872.07   286   274.23  49918.61  24356.196049
Withdrawal                 10811699.35   431   260.53  49841.44  25085.149304
unknown                     1741285.40    73  1808.16  48921.30  23853.224658

                 balance_before_txn_usd
                                    sum count      min       max          mean
transaction_type
Deposit                     11208073.32   474  -801.74  49841.87  23645.724304
Payment                      5869699.48   236  -712.98  49288.75  24871.607966
Transfer                     6839655.89   286 -1102.29  49891.41  23914.880734
Withdrawal                  10595540.86   431  -747.79  49686.87  24583.621485
unknown                      1697956.58    73  1175.45  48812.94  23259.679178

In [35]:
t=data['balance_after_txn_usd'].agg(['sum','count'])
t

sum      36951931.61
count        1500.00
Name: balance_after_txn_usd, dtype: float64

In [40]:
t=pd.pivot_table(
    data=data,
    index='transaction_type',
    columns='channel',
    values='balance_after_txn_usd',
    aggfunc=['sum','count'],
    margins=True,
    fill_value=0,
    margins_name='total amount'
)
t

                         sum                                          \
channel                  ATM      Branch   Mobile App Online Banking
transaction_type
Deposit           1607328.43  1073674.91   5372213.38     3384566.22
Payment           1124975.32   599730.70   2540134.26     1730451.57
Transfer          1229154.72   544014.02   3227113.78     1965589.55
Withdrawal        1993764.52  1329639.90   4846977.43     2641317.50
unknown            271286.83   150719.61    897129.31      422149.65
total amount      6226509.82  3697779.14  16883568.16    10144074.49

                              count                                   \
channel          total amount   ATM Branch Mobile App Online Banking
transaction_type
Deposit           11437782.94    67     43        224            140
Payment            5995291.85    40     25        103             68
Transfer           6965872.07    47     25        130             84
Withdrawal        10811699.35    74     50        193            114
unknown            1741285.40    10      6         37             20
total amount      36951931.61   238    149        687            426


channel          total amount
transaction_type
Deposit                   474
Payment                   236
Transfer                  286
Withdrawal                431
unknown                    73
total amount             1500

In [41]:
data.dtypes

transaction_id                str
account_id                    str
customer_age                int64
account_type                  str
transaction_date              str
transaction_type              str
channel                       str
amount_usd                float64
merchant_category             str
is_fraud_flagged            int64
balance_after_txn_usd     float64
balance_before_txn_usd    float64
dtype: object

In [43]:
data['transaction_date']=pd.to_datetime(data['transaction_date'])
data.dtypes

transaction_id                       str
account_id                           str
customer_age                       int64
account_type                         str
transaction_date          datetime64[us]
transaction_type                     str
channel                              str
amount_usd                       float64
merchant_category                    str
is_fraud_flagged                   int64
balance_after_txn_usd            float64
balance_before_txn_usd           float64
dtype: object

In [54]:
data['month']=data['transaction_date'].dt.month
data

,transaction_id,account_id,customer_age,account_type,transaction_date,transaction_type,channel,amount_usd,merchant_category,is_fraud_flagged,balance_after_txn_usd,balance_before_txn_usd,month
0,TXN_FIN_10000,ACC_0134,24,Savings,2024-09-16,Deposit,Mobile App,788.91,Travel,0,47578.64,46789.73,9
1,TXN_FIN_10001,ACC_0135,47,Investment,2024-04-04,Transfer,Online Banking,102.45,Groceries,0,47621.97,47519.52,4
2,TXN_FIN_10002,ACC_0170,18,Savings,2024-01-30,Withdrawal,Online Banking,108.72,Retail,0,18057.86,17949.14,1
3,TXN_FIN_10003,ACC_0089,72,Checking,2024-01-16,unknown,Mobile App,156.57,Retail,0,3878.63,3722.06,1
4,TXN_FIN_10004,ACC_0157,35,Savings,2024-04-28,Withdrawal,Mobile App,537.51,Retail,0,26920.71,26383.20,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,TXN_FIN_11495,ACC_0038,68,Checking,2024-12-24,Payment,Online Banking,557.69,Entertainment,0,47714.65,47156.96,12
1496,TXN_FIN_11496,ACC_0119,56,Credit Card,2024-11-05,Payment,Online Banking,230.16,Groceries,0,2167.28,1937.12,11
1497,TXN_FIN_11497,ACC_0160,46,Savings,2024-12-22,Payment,Mobile App,801.84,Travel,0,29646.94,28845.10,12
1498,TXN_FIN_11498,ACC_0076,39,Savings,2024-10-14,Payment,ATM,55.91,Entertainment,0,15156.76,15100.85,10
1499,TXN_FIN_11499,ACC_0023,78,Savings,2024-12-26,Payment,Online Banking,8.80,Utilities,0,49264.64,49255.84,12

In [63]:
t=data['transaction_date'].dt.month_name().str[:3]
t

0       Sep
1       Apr
2       Jan
3       Jan
4       Apr
       ...
1495    Dec
1496    Nov
1497    Dec
1498    Oct
1499    Dec
Name: transaction_date, Length: 1500, dtype: str

In [68]:
data=data.drop('month',axis=1)
data

,transaction_id,account_id,customer_age,account_type,transaction_date,transaction_type,channel,amount_usd,merchant_category,is_fraud_flagged,balance_after_txn_usd,balance_before_txn_usd
0,TXN_FIN_10000,ACC_0134,24,Savings,2024-09-16,Deposit,Mobile App,788.91,Travel,0,47578.64,46789.73
1,TXN_FIN_10001,ACC_0135,47,Investment,2024-04-04,Transfer,Online Banking,102.45,Groceries,0,47621.97,47519.52
2,TXN_FIN_10002,ACC_0170,18,Savings,2024-01-30,Withdrawal,Online Banking,108.72,Retail,0,18057.86,17949.14
3,TXN_FIN_10003,ACC_0089,72,Checking,2024-01-16,unknown,Mobile App,156.57,Retail,0,3878.63,3722.06
4,TXN_FIN_10004,ACC_0157,35,Savings,2024-04-28,Withdrawal,Mobile App,537.51,Retail,0,26920.71,26383.20
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,TXN_FIN_11495,ACC_0038,68,Checking,2024-12-24,Payment,Online Banking,557.69,Entertainment,0,47714.65,47156.96
1496,TXN_FIN_11496,ACC_0119,56,Credit Card,2024-11-05,Payment,Online Banking,230.16,Groceries,0,2167.28,1937.12
1497,TXN_FIN_11497,ACC_0160,46,Savings,2024-12-22,Payment,Mobile App,801.84,Travel,0,29646.94,28845.10
1498,TXN_FIN_11498,ACC_0076,39,Savings,2024-10-14,Payment,ATM,55.91,Entertainment,0,15156.76,15100.85
1499,TXN_FIN_11499,ACC_0023,78,Savings,2024-12-26,Payment,Online Banking,8.80,Utilities,0,49264.64,49255.84

In [69]:
data['month']=data['transaction_date'].dt.month_name().str[:3]
data

,transaction_id,account_id,customer_age,account_type,transaction_date,transaction_type,channel,amount_usd,merchant_category,is_fraud_flagged,balance_after_txn_usd,balance_before_txn_usd,month
0,TXN_FIN_10000,ACC_0134,24,Savings,2024-09-16,Deposit,Mobile App,788.91,Travel,0,47578.64,46789.73,Sep
1,TXN_FIN_10001,ACC_0135,47,Investment,2024-04-04,Transfer,Online Banking,102.45,Groceries,0,47621.97,47519.52,Apr
2,TXN_FIN_10002,ACC_0170,18,Savings,2024-01-30,Withdrawal,Online Banking,108.72,Retail,0,18057.86,17949.14,Jan
3,TXN_FIN_10003,ACC_0089,72,Checking,2024-01-16,unknown,Mobile App,156.57,Retail,0,3878.63,3722.06,Jan
4,TXN_FIN_10004,ACC_0157,35,Savings,2024-04-28,Withdrawal,Mobile App,537.51,Retail,0,26920.71,26383.20,Apr
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,TXN_FIN_11495,ACC_0038,68,Checking,2024-12-24,Payment,Online Banking,557.69,Entertainment,0,47714.65,47156.96,Dec
1496,TXN_FIN_11496,ACC_0119,56,Credit Card,2024-11-05,Payment,Online Banking,230.16,Groceries,0,2167.28,1937.12,Nov
1497,TXN_FIN_11497,ACC_0160,46,Savings,2024-12-22,Payment,Mobile App,801.84,Travel,0,29646.94,28845.10,Dec
1498,TXN_FIN_11498,ACC_0076,39,Savings,2024-10-14,Payment,ATM,55.91,Entertainment,0,15156.76,15100.85,Oct
1499,TXN_FIN_11499,ACC_0023,78,Savings,2024-12-26,Payment,Online Banking,8.80,Utilities,0,49264.64,49255.84,Dec

In [84]:
data['day']=data['transaction_date'].dt.day_name().str[:3]
data

,transaction_id,account_id,customer_age,account_type,transaction_date,transaction_type,channel,amount_usd,merchant_category,is_fraud_flagged,balance_after_txn_usd,balance_before_txn_usd,month,day
0,TXN_FIN_10000,ACC_0134,24,Savings,2024-09-16,Deposit,Mobile App,788.91,Travel,0,47578.64,46789.73,Sep,Mon
1,TXN_FIN_10001,ACC_0135,47,Investment,2024-04-04,Transfer,Online Banking,102.45,Groceries,0,47621.97,47519.52,Apr,Thu
2,TXN_FIN_10002,ACC_0170,18,Savings,2024-01-30,Withdrawal,Online Banking,108.72,Retail,0,18057.86,17949.14,Jan,Tue
3,TXN_FIN_10003,ACC_0089,72,Checking,2024-01-16,unknown,Mobile App,156.57,Retail,0,3878.63,3722.06,Jan,Tue
4,TXN_FIN_10004,ACC_0157,35,Savings,2024-04-28,Withdrawal,Mobile App,537.51,Retail,0,26920.71,26383.20,Apr,Sun
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,TXN_FIN_11495,ACC_0038,68,Checking,2024-12-24,Payment,Online Banking,557.69,Entertainment,0,47714.65,47156.96,Dec,Tue
1496,TXN_FIN_11496,ACC_0119,56,Credit Card,2024-11-05,Payment,Online Banking,230.16,Groceries,0,2167.28,1937.12,Nov,Tue
1497,TXN_FIN_11497,ACC_0160,46,Savings,2024-12-22,Payment,Mobile App,801.84,Travel,0,29646.94,28845.10,Dec,Sun
1498,TXN_FIN_11498,ACC_0076,39,Savings,2024-10-14,Payment,ATM,55.91,Entertainment,0,15156.76,15100.85,Oct,Mon
1499,TXN_FIN_11499,ACC_0023,78,Savings,2024-12-26,Payment,Online Banking,8.80,Utilities,0,49264.64,49255.84,Dec,Thu

In [93]:

f=data.to_csv('bank.csv')
f