In [36]:
import os as o
t=o.getcwd()
t

'C:\\Users\\ELCOT\\Downloads'

In [37]:
c=o.chdir(r'C:\Users\ELCOT\Downloads')
t=o.getcwd()
t

'C:\\Users\\ELCOT\\Downloads'

In [38]:
import pandas as pd
data=pd.read_csv('hospital data.csv')
data

,patient_id,admission_id,age,gender,blood_type,admission_date,discharge_date,department,admission_type,treatment_cost_usd,insurance_covered_usd,readmitted,patient_satisfaction
0,PAT_10000,ADM_50000,27,Female,O+,2024-07-23,2024-07-25,Pediatrics,Elective,18618.61,10950.35,Yes,1.0
1,PAT_10001,ADM_50001,46,Male,AB+,2024-01-18,2024-01-27,Orthopedics,Emergency,17384.52,8428.00,No,5.0
2,PAT_10002,ADM_50002,39,Male,A-,2024-06-13,2024-06-15,Orthopedics,Urgent,2770.02,13669.54,No,3.0
3,PAT_10003,ADM_50003,48,Male,O-,2024-11-13,2024-11-20,Orthopedics,Emergency,15095.64,7999.99,No,4.0
4,PAT_10004,ADM_50004,25,Male,O-,2024-10-10,2024-10-11,Pediatrics,Elective,16389.19,19489.31,No,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1500,PAT_10012,ADM_50012,22,Female,AB+,2024-08-19,2024-09-01,Emergency,Emergency,23504.24,5970.99,No,4.0
1501,PAT_10045,ADM_50045,60,Female,AB-,2024-06-30,2024-07-13,Emergency,Elective,13976.16,8889.43,No,3.0
1502,PAT_10088,ADM_50088,41,Female,B-,2024-09-21,2024-09-22,Pediatrics,Elective,19743.10,8862.79,No,5.0
1503,PAT_10105,ADM_50105,63,Female,AB+,2024-08-11,2024-08-21,Orthopedics,Emergency,15993.57,8924.91,No,5.0
1504,PAT_10310,ADM_50310,67,Female,A+,2024-09-17,2024-09-26,Emergency,Emergency,17602.13,333.69,No,4.0

In [39]:
#find errors and duplicates with null
print(data.shape)
print(data.isnull().sum())
print(data.duplicated().sum())
print(data.loc[data.duplicated().sum()])

(1505, 13)
patient_id                0
admission_id              0
age                       0
gender                    0
blood_type                0
admission_date            0
discharge_date            0
department                0
admission_type            0
treatment_cost_usd        0
insurance_covered_usd     0
readmitted               72
patient_satisfaction     71
dtype: int64
5
patient_id                PAT_10005
admission_id              ADM_50005
age                              85
gender                         Male
blood_type                       A+
admission_date           2024-07-16
discharge_date           2024-07-24
department                 Oncology
admission_type            Emergency
treatment_cost_usd          13896.3
insurance_covered_usd        3287.2
readmitted                       No
patient_satisfaction            4.0
Name: 5, dtype: object

In [40]:
#remove duplicate::

data=data.drop_duplicates()
data

,patient_id,admission_id,age,gender,blood_type,admission_date,discharge_date,department,admission_type,treatment_cost_usd,insurance_covered_usd,readmitted,patient_satisfaction
0,PAT_10000,ADM_50000,27,Female,O+,2024-07-23,2024-07-25,Pediatrics,Elective,18618.61,10950.35,Yes,1.0
1,PAT_10001,ADM_50001,46,Male,AB+,2024-01-18,2024-01-27,Orthopedics,Emergency,17384.52,8428.00,No,5.0
2,PAT_10002,ADM_50002,39,Male,A-,2024-06-13,2024-06-15,Orthopedics,Urgent,2770.02,13669.54,No,3.0
3,PAT_10003,ADM_50003,48,Male,O-,2024-11-13,2024-11-20,Orthopedics,Emergency,15095.64,7999.99,No,4.0
4,PAT_10004,ADM_50004,25,Male,O-,2024-10-10,2024-10-11,Pediatrics,Elective,16389.19,19489.31,No,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,PAT_11495,ADM_51495,75,Female,A+,2024-08-05,2024-08-08,Oncology,Urgent,4797.36,15208.54,Yes,4.0
1496,PAT_11496,ADM_51496,79,Male,AB+,2024-01-16,2024-01-22,Cardiology,Emergency,7465.91,17727.42,No,3.0
1497,PAT_11497,ADM_51497,66,Male,AB-,2024-06-14,2024-06-28,Orthopedics,Emergency,13750.80,2649.89,Yes,3.0
1498,PAT_11498,ADM_51498,58,Female,A-,2024-03-08,2024-03-11,Neurology,Emergency,12883.53,1416.42,No,4.0
1499,PAT_11499,ADM_51499,66,Female,AB+,2024-04-23,2024-04-26,Cardiology,Emergency,2072.02,2202.43,No,4.0

In [41]:
data=data.dropna()
data

,patient_id,admission_id,age,gender,blood_type,admission_date,discharge_date,department,admission_type,treatment_cost_usd,insurance_covered_usd,readmitted,patient_satisfaction
0,PAT_10000,ADM_50000,27,Female,O+,2024-07-23,2024-07-25,Pediatrics,Elective,18618.61,10950.35,Yes,1.0
1,PAT_10001,ADM_50001,46,Male,AB+,2024-01-18,2024-01-27,Orthopedics,Emergency,17384.52,8428.00,No,5.0
2,PAT_10002,ADM_50002,39,Male,A-,2024-06-13,2024-06-15,Orthopedics,Urgent,2770.02,13669.54,No,3.0
3,PAT_10003,ADM_50003,48,Male,O-,2024-11-13,2024-11-20,Orthopedics,Emergency,15095.64,7999.99,No,4.0
4,PAT_10004,ADM_50004,25,Male,O-,2024-10-10,2024-10-11,Pediatrics,Elective,16389.19,19489.31,No,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,PAT_11495,ADM_51495,75,Female,A+,2024-08-05,2024-08-08,Oncology,Urgent,4797.36,15208.54,Yes,4.0
1496,PAT_11496,ADM_51496,79,Male,AB+,2024-01-16,2024-01-22,Cardiology,Emergency,7465.91,17727.42,No,3.0
1497,PAT_11497,ADM_51497,66,Male,AB-,2024-06-14,2024-06-28,Orthopedics,Emergency,13750.80,2649.89,Yes,3.0
1498,PAT_11498,ADM_51498,58,Female,A-,2024-03-08,2024-03-11,Neurology,Emergency,12883.53,1416.42,No,4.0
1499,PAT_11499,ADM_51499,66,Female,AB+,2024-04-23,2024-04-26,Cardiology,Emergency,2072.02,2202.43,No,4.0

In [42]:
t=data.isnull().sum()
t

patient_id               0
admission_id             0
age                      0
gender                   0
blood_type               0
admission_date           0
discharge_date           0
department               0
admission_type           0
treatment_cost_usd       0
insurance_covered_usd    0
readmitted               0
patient_satisfaction     0
dtype: int64

In [43]:
t=data.dtypes
t

patient_id                   str
admission_id                 str
age                        int64
gender                       str
blood_type                   str
admission_date               str
discharge_date               str
department                   str
admission_type               str
treatment_cost_usd       float64
insurance_covered_usd    float64
readmitted                   str
patient_satisfaction     float64
dtype: object

In [44]:
data['admission_date']=pd.to_datetime(data['admission_date'])
data['discharge_date']=pd.to_datetime(data['discharge_date'])
print(data.dtypes)

patient_id                          str
admission_id                        str
age                               int64
gender                              str
blood_type                          str
admission_date           datetime64[us]
discharge_date           datetime64[us]
department                          str
admission_type                      str
treatment_cost_usd              float64
insurance_covered_usd           float64
readmitted                          str
patient_satisfaction            float64
dtype: object

In [45]:
f=data['insurance_covered_usd']-data['treatment_cost_usd']
data['amount_paid']=abs(f)
data

,patient_id,admission_id,age,gender,blood_type,admission_date,discharge_date,department,admission_type,treatment_cost_usd,insurance_covered_usd,readmitted,patient_satisfaction,amount_paid
0,PAT_10000,ADM_50000,27,Female,O+,2024-07-23,2024-07-25,Pediatrics,Elective,18618.61,10950.35,Yes,1.0,7668.26
1,PAT_10001,ADM_50001,46,Male,AB+,2024-01-18,2024-01-27,Orthopedics,Emergency,17384.52,8428.00,No,5.0,8956.52
2,PAT_10002,ADM_50002,39,Male,A-,2024-06-13,2024-06-15,Orthopedics,Urgent,2770.02,13669.54,No,3.0,10899.52
3,PAT_10003,ADM_50003,48,Male,O-,2024-11-13,2024-11-20,Orthopedics,Emergency,15095.64,7999.99,No,4.0,7095.65
4,PAT_10004,ADM_50004,25,Male,O-,2024-10-10,2024-10-11,Pediatrics,Elective,16389.19,19489.31,No,4.0,3100.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,PAT_11495,ADM_51495,75,Female,A+,2024-08-05,2024-08-08,Oncology,Urgent,4797.36,15208.54,Yes,4.0,10411.18
1496,PAT_11496,ADM_51496,79,Male,AB+,2024-01-16,2024-01-22,Cardiology,Emergency,7465.91,17727.42,No,3.0,10261.51
1497,PAT_11497,ADM_51497,66,Male,AB-,2024-06-14,2024-06-28,Orthopedics,Emergency,13750.80,2649.89,Yes,3.0,11100.91
1498,PAT_11498,ADM_51498,58,Female,A-,2024-03-08,2024-03-11,Neurology,Emergency,12883.53,1416.42,No,4.0,11467.11
1499,PAT_11499,ADM_51499,66,Female,AB+,2024-04-23,2024-04-26,Cardiology,Emergency,2072.02,2202.43,No,4.0,130.41

In [35]:
def add(amt):
    if amt>=10000:
        data['status']='high paid'
    elif amt>=5000:
        data['status']='medium paid'
    else:
        data['status']='low paid'
data=data['amount_paid'].apply(add)
data

0       None
1       None
2       None
3       None
4       None
        ...
1495    None
1496    None
1497    None
1498    None
1499    None
Name: amount_paid, Length: 1360, dtype: object

In [34]:
g=data.groupby('department')['amount_paid'].agg(['sum','count','max','min','mean'])
g

                    sum  count       max     min         mean
department
Cardiology   1746664.52    210  23763.91    6.38  8317.450095
Emergency    1791318.25    240  22513.10    9.27  7463.826042
Neurology    1857006.01    227  24385.22  157.86  8180.643216
Oncology     1683569.71    216  23090.49  182.60  7794.304213
Orthopedics  1783703.58    223  24405.55  101.88  7998.670762
Pediatrics   1820102.27    244  23478.15   60.33  7459.435533

In [33]:
h=pd.pivot_table(
    data=data,
    index='department',
    columns='admission_type',
    values='amount_paid',
    aggfunc='count',
    fill_value=0,
    margins=True,
    margins_name='no of count in department'
)
h

admission_type,Elective,Emergency,Urgent,no of count in department
department,,,,
Cardiology,61,99,50,210
Emergency,56,123,61,240
Neurology,67,117,43,227
Oncology,63,117,36,216
Orthopedics,71,111,41,223
Pediatrics,69,126,49,244
no of count in department,387,693,280,1360

In [47]:
f=data.to_csv('load.csv')
f