In [1]:
import os as o
t=o.getcwd()
t

'C:\\Users\\ELCOT'

In [3]:
f=o.chdir(r'C:\Users\ELCOT\Downloads')
f
t=o.getcwd()
t

'C:\\Users\\ELCOT\\Downloads'

In [4]:
import pandas as pd
data=pd.read_csv('pd.csv')
data

,transaction_id,customer_id,signup_date,transaction_date,region,category,product_name,price,quantity,discount,payment_method,customer_rating
0,TXN_1000,CUST_103,2023-11-01,2024-07-20,North,Sports,Prod_B,248.82,4,0.20,Net Banking,2.0
1,TXN_1001,CUST_93,2023-10-13,2024-12-10,North,Home,Prod_D,348.79,5,0.05,UPI,4.0
2,TXN_1002,CUST_15,2023-05-24,2024-05-25,East,Home,Prod_D,138.26,1,0.00,Credit Card,3.0
3,TXN_1003,CUST_107,2023-01-19,2024-06-12,West,Clothing,Prod_E,315.88,2,0.15,UPI,3.0
4,TXN_1004,CUST_72,2023-01-18,2024-08-29,North,Electronics,Prod_D,416.40,5,0.15,Credit Card,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
998,TXN_1998,CUST_32,2023-03-01,2024-08-01,North,Clothing,Prod_B,12.39,5,0.05,UPI,5.0
999,TXN_1999,CUST_29,2023-06-16,2024-06-01,South,Clothing,Prod_D,212.21,2,0.05,UPI,4.0
1000,TXN_1010,CUST_117,2023-04-24,2024-06-09,South,Clothing,Prod_D,162.97,5,0.10,Credit Card,4.0
1001,TXN_1025,CUST_59,2023-06-27,2024-09-19,West,Beauty,Prod_D,295.88,2,0.00,Cash,3.0
1002,TXN_1040,CUST_14,2023-04-07,2024-02-11,East,Home,Prod_D,404.75,4,0.00,Net Banking,3.0

In [8]:
#find error::

print(data.shape)
print(data.duplicated().sum())
print(data.isnull().sum())
print(data.loc[data.duplicated()])

(1003, 12)
3
transaction_id       0
customer_id          0
signup_date          0
transaction_date     0
region               0
category             0
product_name         0
price                0
quantity             0
discount            48
payment_method      61
customer_rating     43
dtype: int64
     transaction_id customer_id signup_date transaction_date region  category  \
1000       TXN_1010    CUST_117  2023-04-24       2024-06-09  South  Clothing
1001       TXN_1025     CUST_59  2023-06-27       2024-09-19   West    Beauty
1002       TXN_1040     CUST_14  2023-04-07       2024-02-11   East      Home

     product_name   price  quantity  discount payment_method  customer_rating
1000       Prod_D  162.97         5       0.1    Credit Card              4.0
1001       Prod_D  295.88         2       0.0           Cash              3.0
1002       Prod_D  404.75         4       0.0    Net Banking              3.0

In [9]:
#data cleaning::

data=data.drop_duplicates()
data

,transaction_id,customer_id,signup_date,transaction_date,region,category,product_name,price,quantity,discount,payment_method,customer_rating
0,TXN_1000,CUST_103,2023-11-01,2024-07-20,North,Sports,Prod_B,248.82,4,0.20,Net Banking,2.0
1,TXN_1001,CUST_93,2023-10-13,2024-12-10,North,Home,Prod_D,348.79,5,0.05,UPI,4.0
2,TXN_1002,CUST_15,2023-05-24,2024-05-25,East,Home,Prod_D,138.26,1,0.00,Credit Card,3.0
3,TXN_1003,CUST_107,2023-01-19,2024-06-12,West,Clothing,Prod_E,315.88,2,0.15,UPI,3.0
4,TXN_1004,CUST_72,2023-01-18,2024-08-29,North,Electronics,Prod_D,416.40,5,0.15,Credit Card,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN_1995,CUST_141,2023-06-01,2024-03-12,West,Sports,Prod_D,151.82,4,0.00,UPI,3.0
996,TXN_1996,CUST_123,2023-01-19,2024-03-27,North,Clothing,Prod_E,245.02,5,0.00,NaN,5.0
997,TXN_1997,CUST_62,2023-04-10,2024-09-18,North,Sports,Prod_C,486.69,1,0.20,Credit Card,4.0
998,TXN_1998,CUST_32,2023-03-01,2024-08-01,North,Clothing,Prod_B,12.39,5,0.05,UPI,5.0
999,TXN_1999,CUST_29,2023-06-16,2024-06-01,South,Clothing,Prod_D,212.21,2,0.05,UPI,4.0

In [12]:
print(data.shape)

(1000, 12)

In [13]:
print(data.dtypes)

transaction_id          str
customer_id             str
signup_date             str
transaction_date        str
region                  str
category                str
product_name            str
price               float64
quantity              int64
discount            float64
payment_method          str
customer_rating     float64
dtype: object

In [14]:
data['discount']=data['discount'].fillna(0)
data

,transaction_id,customer_id,signup_date,transaction_date,region,category,product_name,price,quantity,discount,payment_method,customer_rating
0,TXN_1000,CUST_103,2023-11-01,2024-07-20,North,Sports,Prod_B,248.82,4,0.20,Net Banking,2.0
1,TXN_1001,CUST_93,2023-10-13,2024-12-10,North,Home,Prod_D,348.79,5,0.05,UPI,4.0
2,TXN_1002,CUST_15,2023-05-24,2024-05-25,East,Home,Prod_D,138.26,1,0.00,Credit Card,3.0
3,TXN_1003,CUST_107,2023-01-19,2024-06-12,West,Clothing,Prod_E,315.88,2,0.15,UPI,3.0
4,TXN_1004,CUST_72,2023-01-18,2024-08-29,North,Electronics,Prod_D,416.40,5,0.15,Credit Card,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN_1995,CUST_141,2023-06-01,2024-03-12,West,Sports,Prod_D,151.82,4,0.00,UPI,3.0
996,TXN_1996,CUST_123,2023-01-19,2024-03-27,North,Clothing,Prod_E,245.02,5,0.00,NaN,5.0
997,TXN_1997,CUST_62,2023-04-10,2024-09-18,North,Sports,Prod_C,486.69,1,0.20,Credit Card,4.0
998,TXN_1998,CUST_32,2023-03-01,2024-08-01,North,Clothing,Prod_B,12.39,5,0.05,UPI,5.0
999,TXN_1999,CUST_29,2023-06-16,2024-06-01,South,Clothing,Prod_D,212.21,2,0.05,UPI,4.0

In [15]:
print(data.isnull().sum())

transaction_id       0
customer_id          0
signup_date          0
transaction_date     0
region               0
category             0
product_name         0
price                0
quantity             0
discount             0
payment_method      61
customer_rating     43
dtype: int64

In [17]:
data['payment_method']=data['payment_method'].fillna('unknown')
data['customer_rating']=data['customer_rating'].fillna(data['customer_rating'].median())
data

,transaction_id,customer_id,signup_date,transaction_date,region,category,product_name,price,quantity,discount,payment_method,customer_rating
0,TXN_1000,CUST_103,2023-11-01,2024-07-20,North,Sports,Prod_B,248.82,4,0.20,Net Banking,2.0
1,TXN_1001,CUST_93,2023-10-13,2024-12-10,North,Home,Prod_D,348.79,5,0.05,UPI,4.0
2,TXN_1002,CUST_15,2023-05-24,2024-05-25,East,Home,Prod_D,138.26,1,0.00,Credit Card,3.0
3,TXN_1003,CUST_107,2023-01-19,2024-06-12,West,Clothing,Prod_E,315.88,2,0.15,UPI,3.0
4,TXN_1004,CUST_72,2023-01-18,2024-08-29,North,Electronics,Prod_D,416.40,5,0.15,Credit Card,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN_1995,CUST_141,2023-06-01,2024-03-12,West,Sports,Prod_D,151.82,4,0.00,UPI,3.0
996,TXN_1996,CUST_123,2023-01-19,2024-03-27,North,Clothing,Prod_E,245.02,5,0.00,unknown,5.0
997,TXN_1997,CUST_62,2023-04-10,2024-09-18,North,Sports,Prod_C,486.69,1,0.20,Credit Card,4.0
998,TXN_1998,CUST_32,2023-03-01,2024-08-01,North,Clothing,Prod_B,12.39,5,0.05,UPI,5.0
999,TXN_1999,CUST_29,2023-06-16,2024-06-01,South,Clothing,Prod_D,212.21,2,0.05,UPI,4.0

In [18]:
print(data.isnull().sum())

transaction_id      0
customer_id         0
signup_date         0
transaction_date    0
region              0
category            0
product_name        0
price               0
quantity            0
discount            0
payment_method      0
customer_rating     0
dtype: int64

In [21]:
# column datatype conversions::
data['signup_date']=pd.to_datetime(data['signup_date'])
data

,transaction_id,customer_id,signup_date,transaction_date,region,category,product_name,price,quantity,discount,payment_method,customer_rating
0,TXN_1000,CUST_103,2023-11-01,2024-07-20,North,Sports,Prod_B,248.82,4,0.20,Net Banking,2.0
1,TXN_1001,CUST_93,2023-10-13,2024-12-10,North,Home,Prod_D,348.79,5,0.05,UPI,4.0
2,TXN_1002,CUST_15,2023-05-24,2024-05-25,East,Home,Prod_D,138.26,1,0.00,Credit Card,3.0
3,TXN_1003,CUST_107,2023-01-19,2024-06-12,West,Clothing,Prod_E,315.88,2,0.15,UPI,3.0
4,TXN_1004,CUST_72,2023-01-18,2024-08-29,North,Electronics,Prod_D,416.40,5,0.15,Credit Card,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN_1995,CUST_141,2023-06-01,2024-03-12,West,Sports,Prod_D,151.82,4,0.00,UPI,3.0
996,TXN_1996,CUST_123,2023-01-19,2024-03-27,North,Clothing,Prod_E,245.02,5,0.00,unknown,5.0
997,TXN_1997,CUST_62,2023-04-10,2024-09-18,North,Sports,Prod_C,486.69,1,0.20,Credit Card,4.0
998,TXN_1998,CUST_32,2023-03-01,2024-08-01,North,Clothing,Prod_B,12.39,5,0.05,UPI,5.0
999,TXN_1999,CUST_29,2023-06-16,2024-06-01,South,Clothing,Prod_D,212.21,2,0.05,UPI,4.0

In [22]:
data['transaction_date']=pd.to_datetime(data['transaction_date'])
print(data.dtypes)

transaction_id                 str
customer_id                    str
signup_date         datetime64[us]
transaction_date    datetime64[us]
region                         str
category                       str
product_name                   str
price                      float64
quantity                     int64
discount                   float64
payment_method                 str
customer_rating            float64
dtype: object

In [25]:
data['price']=data['price'].astype(float)
print(data.dtypes)

transaction_id                 str
customer_id                    str
signup_date         datetime64[us]
transaction_date    datetime64[us]
region                         str
category                       str
product_name                   str
price                      float64
quantity                     int64
discount                   float64
payment_method                 str
customer_rating            float64
dtype: object

In [26]:
data['gross_amount']=data['price']*data['quantity']
data['discount_amount']=data['gross_amount']*data['discount']
data['final_amount']=data['gross_amount']-data['discount_amount']
data

,transaction_id,customer_id,signup_date,transaction_date,region,category,product_name,price,quantity,discount,payment_method,customer_rating,gross_amount,discount_amount,final_amount
0,TXN_1000,CUST_103,2023-11-01,2024-07-20,North,Sports,Prod_B,248.0,4,0.20,Net Banking,2.0,992.0,198.4,793.6
1,TXN_1001,CUST_93,2023-10-13,2024-12-10,North,Home,Prod_D,348.0,5,0.05,UPI,4.0,1740.0,87.0,1653.0
2,TXN_1002,CUST_15,2023-05-24,2024-05-25,East,Home,Prod_D,138.0,1,0.00,Credit Card,3.0,138.0,0.0,138.0
3,TXN_1003,CUST_107,2023-01-19,2024-06-12,West,Clothing,Prod_E,315.0,2,0.15,UPI,3.0,630.0,94.5,535.5
4,TXN_1004,CUST_72,2023-01-18,2024-08-29,North,Electronics,Prod_D,416.0,5,0.15,Credit Card,3.0,2080.0,312.0,1768.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN_1995,CUST_141,2023-06-01,2024-03-12,West,Sports,Prod_D,151.0,4,0.00,UPI,3.0,604.0,0.0,604.0
996,TXN_1996,CUST_123,2023-01-19,2024-03-27,North,Clothing,Prod_E,245.0,5,0.00,unknown,5.0,1225.0,0.0,1225.0
997,TXN_1997,CUST_62,2023-04-10,2024-09-18,North,Sports,Prod_C,486.0,1,0.20,Credit Card,4.0,486.0,97.2,388.8
998,TXN_1998,CUST_32,2023-03-01,2024-08-01,North,Clothing,Prod_B,12.0,5,0.05,UPI,5.0,60.0,3.0,57.0
999,TXN_1999,CUST_29,2023-06-16,2024-06-01,South,Clothing,Prod_D,212.0,2,0.05,UPI,4.0,424.0,21.2,402.8

In [33]:
r_group=data.groupby('region')['final_amount'].agg(['sum','min','max','mean','count'])
r_group

              sum    min     max        mean  count
region
East    142720.15  11.00  2345.0  706.535396    202
North   197471.35  10.45  2480.0  720.698358    274
South   205697.95  12.00  2410.0  655.089013    314
West    138267.65   9.90  2450.0  658.417381    210

In [34]:
t=r_group[(r_group['sum']>142720.15) ]
t

              sum    min     max        mean  count
region
North   197471.35  10.45  2480.0  720.698358    274
South   205697.95  12.00  2410.0  655.089013    314

In [36]:
f=t[t['count']>300]
f

              sum   min     max        mean  count
region
South   205697.95  12.0  2410.0  655.089013    314

In [37]:
v=data['customer_rating'].median()
v

np.float64(4.0)

In [41]:
c=data[data['customer_rating']>4]
c

,transaction_id,customer_id,signup_date,transaction_date,region,category,product_name,price,quantity,discount,payment_method,customer_rating,gross_amount,discount_amount,final_amount
6,TXN_1006,CUST_103,2023-03-19,2024-06-23,South,Home,Prod_D,459.0,3,0.20,unknown,5.0,1377.0,275.4,1101.6
9,TXN_1009,CUST_88,2023-04-23,2024-08-13,South,Electronics,Prod_E,221.0,2,0.05,Credit Card,5.0,442.0,22.1,419.9
11,TXN_1011,CUST_100,2023-08-10,2024-04-28,South,Home,Prod_D,365.0,3,0.00,Cash,5.0,1095.0,0.0,1095.0
12,TXN_1012,CUST_104,2023-06-15,2024-05-28,South,Clothing,Prod_B,400.0,4,0.10,Credit Card,5.0,1600.0,160.0,1440.0
13,TXN_1013,CUST_131,2023-11-15,2024-05-29,South,Beauty,Prod_C,418.0,2,0.00,UPI,5.0,836.0,0.0,836.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,TXN_1982,CUST_114,2023-01-10,2024-05-11,East,Home,Prod_A,467.0,2,0.00,Net Banking,5.0,934.0,0.0,934.0
985,TXN_1985,CUST_84,2023-06-19,2024-01-28,East,Home,Prod_E,197.0,1,0.00,Net Banking,5.0,197.0,0.0,197.0
994,TXN_1994,CUST_1,2023-02-19,2024-09-13,South,Sports,Prod_C,482.0,5,0.00,Net Banking,5.0,2410.0,0.0,2410.0
996,TXN_1996,CUST_123,2023-01-19,2024-03-27,North,Clothing,Prod_E,245.0,5,0.00,unknown,5.0,1225.0,0.0,1225.0
998,TXN_1998,CUST_32,2023-03-01,2024-08-01,North,Clothing,Prod_B,12.0,5,0.05,UPI,5.0,60.0,3.0,57.0

In [46]:
sum_of_final=data['final_amount'].agg(['sum','min','max','mean','count'])
sum_of_final

sum      684157.1000
min           9.9000
max        2480.0000
mean        684.1571
count      1000.0000
Name: final_amount, dtype: float64

In [51]:
v_group=data.groupby('region')[['final_amount','quantity','customer_rating']].agg(['sum','min','max','mean','count'])
v_group

       final_amount                                  quantity          \
                sum    min     max        mean count      sum min max
region
East      142720.15  11.00  2345.0  706.535396   202      594   1   5
North     197471.35  10.45  2480.0  720.698358   274      853   1   5
South     205697.95  12.00  2410.0  655.089013   314      888   1   5
West      138267.65   9.90  2450.0  658.417381   210      625   1   5

                       customer_rating
            mean count             sum  min  max      mean count
region
East    2.940594   202           733.0  1.0  5.0  3.628713   202
North   3.113139   274          1012.0  1.0  5.0  3.693431   274
South   2.828025   314          1161.0  1.0  5.0  3.697452   314
West    2.976190   210           824.0  1.0  5.0  3.923810   210

In [52]:
c_group=data.groupby('category')[['final_amount','quantity','customer_rating']].agg(['sum','min','max','mean','count'])
c_group

            final_amount                                  quantity          \
                     sum    min     max        mean count      sum min max
category
Beauty         146522.40  19.00  2450.0  701.064115   209      632   1   5
Clothing       146606.35   9.90  2230.0  708.243237   207      618   1   5
Electronics    115068.15  11.00  2345.0  657.532286   175      495   1   5
Home           131250.00  12.00  2240.0  649.752475   202      614   1   5
Sports         144710.20  10.45  2480.0  699.083092   207      601   1   5

                            customer_rating
                 mean count             sum  min  max      mean count
category
Beauty       3.023923   209           791.0  1.0  5.0  3.784689   209
Clothing     2.985507   207           799.0  1.0  5.0  3.859903   207
Electronics  2.828571   175           646.0  1.0  5.0  3.691429   175
Home         3.039604   202           736.0  1.0  5.0  3.643564   202
Sports       2.903382   207           758.0  1.0  5.0  3.661836   207

In [53]:
h=data.head(4)
h

,transaction_id,customer_id,signup_date,transaction_date,region,category,product_name,price,quantity,discount,payment_method,customer_rating,gross_amount,discount_amount,final_amount
0,TXN_1000,CUST_103,2023-11-01,2024-07-20,North,Sports,Prod_B,248.0,4,0.20,Net Banking,2.0,992.0,198.4,793.6
1,TXN_1001,CUST_93,2023-10-13,2024-12-10,North,Home,Prod_D,348.0,5,0.05,UPI,4.0,1740.0,87.0,1653.0
2,TXN_1002,CUST_15,2023-05-24,2024-05-25,East,Home,Prod_D,138.0,1,0.00,Credit Card,3.0,138.0,0.0,138.0
3,TXN_1003,CUST_107,2023-01-19,2024-06-12,West,Clothing,Prod_E,315.0,2,0.15,UPI,3.0,630.0,94.5,535.5

In [60]:
f=h.query("region == 'North' and quantity>4")
f

,transaction_id,customer_id,signup_date,transaction_date,region,category,product_name,price,quantity,discount,payment_method,customer_rating,gross_amount,discount_amount,final_amount
1,TXN_1001,CUST_93,2023-10-13,2024-12-10,North,Home,Prod_D,348.0,5,0.05,UPI,4.0,1740.0,87.0,1653.0

In [64]:
pivot_advanced = pd.pivot_table(
    data=data,
    values=['final_amount', 'quantity'],
    index='region',
    columns='category',
    aggfunc={'final_amount': 'sum', 'quantity': 'mean'},
    fill_value=0,
    margins=True,
    margins_name='Total'
)

print(pivot_advanced)

         final_amount                                                          \
category       Beauty   Clothing Electronics       Home     Sports      Total
region
East         28252.95   28825.35    27886.95   26852.40   30902.50  142720.15
North        43352.60   46695.80    32136.95   39377.25   35908.75  197471.35
South        39516.65   48717.40    23306.10   44670.20   49487.60  205697.95
West         35400.20   22367.80    31738.15   20350.15   28411.35  138267.65
Total       146522.40  146606.35   115068.15  131250.00  144710.20  684157.10

          quantity
category    Beauty  Clothing Electronics      Home    Sports     Total
region
East      3.022727  3.303030    2.888889  2.804348  2.767442  2.940594
North     3.254545  3.169231    2.959184  3.269231  2.886792  3.113139
South     2.703125  2.763889    2.565217  3.045455  2.984848  2.828025
West      3.195652  2.810811    2.909091  3.000000  2.933333  2.976190
Total     3.023923  2.985507    2.828571  3.039604  2.903382  2.960000

In [ ]:
pivot=pd.pivot_table(data=data,index='category',columns='region',values='final_amount',aggfunc='sum'